const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

const generateInvoicePDF = async (invoice) => {
    const browser = await puppeteer.launch({ headless: 'new' });
    const page = await browser.newPage();

    const htmlContent = `
    <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; padding: 20px; }
                .header { text-align: center; margin-bottom: 20px; }
                .details { margin-bottom: 20px; }
                .footer { text-align: center; margin-top: 50px; font-size: 12px; color: #666; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Invoice #${invoice.id.slice(0, 8)}</h1>
            </div>
            <div class="details">
                <p><strong>Customer:</strong> ${invoice.customerName}</p>
                <p><strong>Description:</strong> ${invoice.description}</p>
                <p><strong>Amount:</strong> $${invoice.amount.toFixed(2)}</p>
                <p><strong>Due Date:</strong> ${new Date(invoice.dueDate).toLocaleDateString()}</p>
                <p><strong>Status:</strong> ${invoice.status}</p>
            </div>
            <div class="footer">
                <p>Generated by PayPilot</p>
            </div>
        </body>
    </html>
    `;

    await page.setContent(htmlContent);
    const pdfPath = path.join(__dirname, `../../invoices/invoice_${invoice.id}.pdf`);

    // Ensure directory exists
    const dir = path.dirname(pdfPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    await page.pdf({ path: pdfPath, format: 'A4' });

    await browser.close();
    return pdfPath;
};

module.exports = { generateInvoicePDF };
